### ISSUE TITLE
profile 422

### ISSUE THREAD

**Issue by Discograp** [Patman86/x265-Mod-by-Patman#13]
StaxRip v.2.29.0

Profile 422 does not work in 265 codec - completely

and when selecting 422 in the 264 codec, you must manually specify 422 for input and output - it does not work in automatic mode

**Comment by Discograp** [comment]
Weird
In Hybrid software, these profiles work 50/50

264 8/10-bit high422
265 8/10-bit main422

at video resolution 1080p and below - no problem

and at 2160p - only resize or the usual change/conversion of the codec with upscale, and when changing the FPS - using deinterlacing or interpolation - it works in vapoursynth mode with codec tune: Fast Decode, and in avisynth mode it freezes

**Comment by Patman86** [comment]
Hi. Have you ever tested your settings with the unmodified versions of x264 and x265?

**Comment by Discograp** [comment]
Hello! I haven't changed these codecs. Downloaded the latest versions of StaxRip and Hybrid.

I always used the “standard” 264/265 8/10-bit 420 - no problem

then recently I tried 422 - and all these strange bugs and errors started

PS
where can I get the “official” 264/265? do they process without errors?

8/10 bits
420/422
color range: FULL

**Comment by Patman86** [comment]
Please make a backup of the two files x264.exe and x265.exe in the folder 64bit of Hybrid. Then copy the two exe files from the Staxrip directory (Apps/Encoder/x264 or x265) into the Hybrid folder and test your procedures with Hybrid again. If all this works without problems, it is not due to x264 or x265.

**Comment by Discograp** [comment]
Hello! 

1. Hybrid freeze
2. StaxRip not work

https://drive.google.com/file/d/1x1iFoBEa_v66s3t2Xht7O4VWJxfhM3Aw/view?usp=drive_link

PS
please answer, 

what launcher/software do you use for these codecs and also these filters/scripts: qtgmc, interframe. avsFPS, and rife-app?

**Comment by Patman86** [comment]
Thank you very much for providing your files. x265 with profile 422-10 also works in staxrip and with my x265 version. In hybrid, the convertto filter is used for this, which you have to add manually in staxrip. I'm attaching a few excerpts for you.

hybrid log:

![grafik](https://github.com/Patman86/x265-Mod-by-Patman/assets/54327252/ffee5002-3921-4371-a781-825549deae2f)

staxrip:

![grafik](https://github.com/Patman86/x265-Mod-by-Patman/assets/54327252/00456ac0-c3c9-4219-942a-bea733d012c9)
![grafik](https://github.com/Patman86/x265-Mod-by-Patman/assets/54327252/3a93b413-5a97-42c1-9074-dc2674c99992)


To answer your question, I only use Staxrip and almost no filters because I only use AVC Remux. I use filters when certain things need to be tested.

**Comment by Discograp** [comment]
Thank you! I'll wait for the "fix/corrected" files; I myself don't know how to change codes/scripts, I can only replace ready-made folders/files. and in Hybrid all the files are scattered =)

in the Hybrid only CPU codecs and qtgmc and interframe and rife-app are well implemented
and in StaxRip all modifications 264/265 + qtgmc + avsFPS are well implemented
i.e
x264/x265 and NVenc/QSVenc

**Comment by Discograp** [comment]
maybe it will help
mode - Fast Decode
When this mode is activated, the codec processes UHD content faster and without loss of quality

only UHD, but in HD and SD it is useless

**Comment by Discograp** [comment]
I probably misunderstood
basic/standard profile 422

in mode

x264 high422 8/10-bit

x265 main422 8/10-bit

in automatic mode they do not work
you have to change settings every time, a lot of clicks

in the near future, yes already, all content will be UHD

1. will you correct these profiles? so that they work without capriciousness, right away.

**Comment by Patman86** [comment]
Hi Discograp,

you should rather push your request towards StaxRip, because x265 and x264 are only pure encoders and you have to do all settings by hand. StaxRip does the analysis of the source file and passes this data on. Either you use the issue tracker at StaxRip on GitHub or you join the Discord server of StaxRip.

**Comment by Discograp** [comment]
aah ok

I see, thank you for your reply

**Comment by Discograp** [comment]
PS
the Discord server of StaxRip - a year ago, I entered this chat channel and realized that it was not “active” - there are links with transitions, but they are outdated. There is no "chat" for communication, as the function is disabled

and here – Github channel – my account was banned without explaining why?
